name: document-engine-frontend

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  app:
    profiles: [app]
    container_name: def-frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: document-engine-frontend:local
    restart: unless-stopped
    develop:
      watch:
        - path: src/
          action: rebuild
        - path: public/
          action: rebuild
        - path: angular.json
          action: rebuild
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        - path: nginx.conf
          action: rebuild
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    logging: *default-logging
